// ─── Memory facets — the Knows screen's vocabulary ──────────────────────────
// Pure functions only. No database, no `server-only`: the API route, the React
// view, and the tests all import the SAME rules, so "what bucket is this in"
// and "what does the provenance line say" can never drift between them.
//
// Two facets were added to agent_memory in migration 0358:
//
//   category      rooms | people | rhythm | vendors | guests — the five groups
//                 the manager sees. The DATABASE classifies (a trigger calls
//                 staxis_classify_memory_category) so every write path is
//                 covered, including the LLM-authored `remember` tool. The job
//                 HERE is the inverse: coerce a category that came back from a
//                 model or a browser into the valid set, never trusting it.
//
//   review_state  unreviewed | confirmed. Unreviewed = extracted from pasted
//                 text or an uploaded file and not yet approved by a human.
//                 Those rows are excluded from the copilot's per-turn read;
//                 this module only decides how they LOOK.

export const MEMORY_CATEGORIES = ['rooms', 'people', 'rhythm', 'vendors', 'guests'] as const;
export type MemoryCategory = (typeof MEMORY_CATEGORIES)[number];

/**
 * The bucket a fact lands in when nothing else matches. Mirrors the SQL
 * classifier's fallback in 0358 — a fact we can't place is a fact about how
 * this hotel runs. Changing this means changing the migration too.
 */
export const DEFAULT_MEMORY_CATEGORY: MemoryCategory = 'rhythm';

export type MemoryReviewState = 'unreviewed' | 'confirmed';

export function isMemoryCategory(v: unknown): v is MemoryCategory {
  return typeof v === 'string' && (MEMORY_CATEGORIES as readonly string[]).includes(v);
}

/**
 * Coerce an untrusted category (model output, request body, a stale client) to
 * a valid bucket. NEVER throws and never returns null — a bad value becomes the
 * safe default rather than a 500 or a NULL hole.
 */
export function coerceMemoryCategory(v: unknown): MemoryCategory {
  if (typeof v !== 'string') return DEFAULT_MEMORY_CATEGORY;
  const normalized = v.trim().toLowerCase();
  return isMemoryCategory(normalized) ? normalized : DEFAULT_MEMORY_CATEGORY;
}

// ─── Labels ─────────────────────────────────────────────────────────────────

export interface CategoryLabel {
  title: { en: string; es: string };
  /** One line saying what belongs in this bucket — shown under the heading. */
  hint: { en: string; es: string };
}

export const CATEGORY_LABELS: Record<MemoryCategory, CategoryLabel> = {
  rooms: {
    title: { en: 'Rooms & quirks', es: 'Habitaciones y detalles' },
    hint: {
      en: 'What breaks, what is different, what to watch',
      es: 'Qué se rompe, qué es distinto, qué vigilar',
    },
  },
  people: {
    title: { en: 'People', es: 'Personas' },
    hint: {
      en: 'Who does what, and how your team works',
      es: 'Quién hace qué, y cómo trabaja tu equipo',
    },
  },
  rhythm: {
    title: { en: 'Rhythm', es: 'Ritmo' },
    hint: {
      en: 'How the hotel runs — busy days, timings, routines',
      es: 'Cómo funciona el hotel: días ocupados, horarios, rutinas',
    },
  },
  vendors: {
    title: { en: 'Vendors', es: 'Proveedores' },
    hint: { en: 'Who to call, and for what', es: 'A quién llamar, y para qué' },
  },
  guests: {
    title: { en: 'Guest info', es: 'Información de huéspedes' },
    hint: {
      en: 'Patterns in what guests ask for and complain about',
      es: 'Patrones en lo que piden y reclaman los huéspedes',
    },
  },
};

// ─── Provenance ─────────────────────────────────────────────────────────────

export type MemorySourceLike =
  | 'explicit_user'
  | 'correction'
  | 'operational'
  | 'consolidation'
  | 'inferred'
  | (string & {});

/**
 * Where an OPERATIONAL fact came from, decoded from the stable topic slug
 * generated by src/lib/agent/operational-signals.ts. Naming the actual feed
 * ("from your work orders") is the difference between a manager trusting the
 * line and dismissing it as a black box.
 */
export function operationalEvidence(topic: string, lang: 'en' | 'es'): string {
  const t = (topic || '').toLowerCase();
  const es = lang === 'es';
  if (t.startsWith('op_maint')) return es ? 'de tus órdenes de trabajo' : 'from your work orders';
  if (t.startsWith('op_complaint')) return es ? 'de las quejas registradas' : 'from logged complaints';
  if (t.startsWith('op_noise_floor')) return es ? 'de las quejas por ruido' : 'from noise complaints';
  if (t.startsWith('op_inspect_fail')) return es ? 'de las inspecciones de habitación' : 'from room inspections';
  if (t.startsWith('op_clean_slow')) return es ? 'de los tiempos de limpieza' : 'from cleaning times';
  return es ? 'de los registros de tu hotel' : "from your hotel's own records";
}

/** Short, locale-appropriate date ("Jul 12" / "12 jul"). */
export function shortDate(iso: string, lang: 'en' | 'es', timeZone?: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  try {
    return new Intl.DateTimeFormat(lang === 'es' ? 'es-ES' : 'en-US', {
      month: 'short',
      day: 'numeric',
      ...(timeZone ? { timeZone } : {}),
    }).format(d);
  } catch {
    return iso.slice(0, 10);
  }
}

export interface ProvenanceInput {
  source: MemorySourceLike;
  topic: string;
  /** Display-name snapshot of the author, or the origin of an extracted fact. */
  createdByName: string | null;
  updatedAt: string;
}

/**
 * The plain-English "where I learned this" line. One sentence, no jargon —
 * this is the trust surface, so it must read like a person explaining
 * themselves, not like a database column.
 */
export function provenanceLine(
  input: ProvenanceInput,
  lang: 'en' | 'es',
  timeZone?: string,
): string {
  const es = lang === 'es';
  const when = shortDate(input.updatedAt, lang, timeZone);
  const suffix = when ? ` — ${when}` : '';

  switch (input.source) {
    case 'explicit_user':
    case 'correction': {
      const who = input.createdByName?.trim();
      const head = es ? 'Tú me lo dijiste' : 'You told me';
      return who ? `${head} (${who})${suffix}` : `${head}${suffix}`;
    }
    case 'operational': {
      const head = es ? 'Lo noté' : 'I noticed';
      return `${head} — ${operationalEvidence(input.topic, lang)}${when ? ` · ${when}` : ''}`;
    }
    case 'consolidation':
      return `${es ? 'Lo aprendí de nuestras conversaciones' : 'I learned from our conversations'}${suffix}`;
    case 'inferred': {
      const origin = input.createdByName?.trim();
      const head = es ? 'De lo que compartiste' : 'From what you shared';
      return origin ? `${head} (${origin})${suffix}` : `${head}${suffix}`;
    }
    default:
      return `${es ? 'Origen desconocido' : 'Source unknown'}${suffix}`;
  }
}

// ─── Status ─────────────────────────────────────────────────────────────────

export type FactStatusKind = 'unreviewed' | 'expiring' | 'confirmed';

export interface FactStatus {
  kind: FactStatusKind;
  /** Whole days until expiry, for kind === 'expiring'. Never negative. */
  daysLeft: number | null;
}

export interface FactStatusInput {
  reviewState: MemoryReviewState;
  expiresAt: string | null;
}

/**
 * Unreviewed always wins: a fact awaiting a human is not "confirmed, expiring
 * in 60 days", it is simply not established yet. An already-expired row should
 * not be in the list at all (the read filters it) — if one slips through we
 * report 0 days left rather than a negative countdown.
 */
export function factStatus(input: FactStatusInput, nowMs: number = Date.now()): FactStatus {
  if (input.reviewState === 'unreviewed') return { kind: 'unreviewed', daysLeft: null };
  if (!input.expiresAt) return { kind: 'confirmed', daysLeft: null };
  const at = new Date(input.expiresAt).getTime();
  if (Number.isNaN(at)) return { kind: 'confirmed', daysLeft: null };
  const daysLeft = Math.max(0, Math.ceil((at - nowMs) / 86400_000));
  return { kind: 'expiring', daysLeft };
}

export function statusLabel(status: FactStatus, lang: 'en' | 'es'): string {
  const es = lang === 'es';
  switch (status.kind) {
    case 'unreviewed':
      return es ? 'Sin confirmar' : 'Not confirmed yet';
    case 'expiring':
      return status.daysLeft === 1
        ? (es ? 'Expira en 1 día' : 'Expires in 1 day')
        : (es ? `Expira en ${status.daysLeft} días` : `Expires in ${status.daysLeft} days`);
    default:
      return es ? 'Confirmado' : 'Confirmed';
  }
}

// ─── Grouping ───────────────────────────────────────────────────────────────

export interface GroupableFact {
  category: MemoryCategory;
}

export interface FactGroup<T extends GroupableFact> {
  category: MemoryCategory;
  items: T[];
}

/**
 * Group facts into the five buckets IN THE DECLARED ORDER, keeping input order
 * within each bucket. Every category is returned — including empty ones — so
 * the caller decides whether to render an empty group; a grouping function that
 * silently drops empty buckets makes "you have nothing under Vendors" invisible.
 * A row carrying an out-of-range category is coerced, never dropped.
 */
export function groupFactsByCategory<T extends GroupableFact>(facts: readonly T[]): FactGroup<T>[] {
  const buckets = new Map<MemoryCategory, T[]>();
  for (const c of MEMORY_CATEGORIES) buckets.set(c, []);
  for (const f of facts) {
    buckets.get(coerceMemoryCategory(f.category))!.push(f);
  }
  return MEMORY_CATEGORIES.map((category) => ({ category, items: buckets.get(category)! }));
}
