-- Phase 2B / Door B fix (audit 2026-05-22) — RLS sweep.
-- Auto-generated by scripts/generate-mfa-rls-sweep.mjs from prod
-- pg_policies. Every authenticated/public policy gets the
-- mfa_verified_or_grace() gate AND-ed to its existing USING /
-- WITH CHECK clauses.
--
-- Apply order: 0159 (table + helper) → 0160 (hook v2) → wait
-- ~5-10min for active sessions to refresh tokens → THIS migration
-- (0161) → wait 24h → 0162 (tighten coalesce default to false).

-- ── Pre-flight: refuse to apply if 0159 not in place yet ──────
-- Without the helper function, every gated policy will fail to
-- evaluate and deny every authenticated read. Loud fail > silent
-- breakage.
do $$ begin
  if to_regprocedure('public.mfa_verified_or_grace()') is null then
    raise exception 'apply migration 0159 first — mfa_verified_or_grace function missing';
  end if;
end$$;

-- ── Skipped (informational, no SQL emitted) ───────────────────
-- SKIP accounts:account can read self: EXEMPT
-- SKIP accounts:accounts_deny_writes: EXEMPT
-- SKIP accounts:accounts_self_select: EXEMPT
-- SKIP agent_conversations_archived:agent_conversations_archived_deny_all_browser: deny-all (USING false)
-- SKIP agent_eval_baselines:agent_eval_baselines_deny_all_browser: deny-all (USING false)
-- SKIP agent_messages_archived:agent_messages_archived_deny_all_browser: deny-all (USING false)
-- SKIP agent_prompts:agent_prompts_deny_all_browser: deny-all (USING false)
-- SKIP agent_voice_sessions:agent_voice_sessions_deny_all_browser: deny-all (USING false)
-- SKIP applied_migrations:applied_migrations_deny_browser: deny-all (USING false)
-- SKIP cron_heartbeats:cron_heartbeats_deny_browser: deny-all (USING false)
-- SKIP error_logs:error_logs_deny_all_browser: deny-all (USING false)
-- SKIP idempotency_log:idempotency_log_deny_browser: deny-all (USING false)
-- SKIP onboarding_jobs:onboarding_jobs_deny_browser: deny-all (USING false)
-- SKIP password_signin_proofs:password_signin_proofs_auth_admin_all: service-role only (supabase_auth_admin)
-- SKIP pms_recipes:pms_recipes_deny_browser: deny-all (USING false)
-- SKIP processed_sentry_webhooks:processed_sentry_webhooks_deny_browser: deny-all (USING false)
-- SKIP processed_twilio_webhooks:processed_twilio_webhooks_deny_browser: deny-all (USING false)
-- SKIP property_shift_presets:property_shift_presets_deny_writes: deny-all (USING false)
-- SKIP pull_jobs:pull_jobs_deny_browser: deny-all (USING false)
-- SKIP pull_metrics:pull_metrics_deny_all_browser: deny-all (USING false)
-- SKIP scheduled_shifts:scheduled_shifts_deny_writes: deny-all (USING false)
-- SKIP scraper_credentials:scraper_credentials_deny_browser: deny-all (USING false)
-- SKIP scraper_session:scraper_session_deny_all_browser: deny-all (USING false)
-- SKIP sms_jobs:sms_jobs_deny_browser: deny-all (USING false)
-- SKIP stripe_processed_events:stripe_processed_events_deny_browser: deny-all (USING false)
-- SKIP time_off_requests:time_off_requests_deny_writes: deny-all (USING false)
-- SKIP webhook_log:webhook_log_deny_all_browser: deny-all (USING false)
-- SKIP week_publications:week_publications_deny_writes: deny-all (USING false)

-- ── Gated policies (57 total) ─────────────────────

-- account_invites:account_invites_manage_for_own_hotels (cmd=ALL)
alter policy "account_invites_manage_for_own_hotels" on public.account_invites
  using ((user_owns_property(hotel_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(hotel_id)) and public.mfa_verified_or_grace());

-- agent_conversations:agent_conversations_select_own (cmd=SELECT)
alter policy "agent_conversations_select_own" on public.agent_conversations
  using (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.id = agent_conversations.user_id) AND (a.data_user_id = auth.uid()))))) and public.mfa_verified_or_grace());

-- agent_costs:agent_costs_select_own (cmd=SELECT)
alter policy "agent_costs_select_own" on public.agent_costs
  using (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.id = agent_costs.user_id) AND (a.data_user_id = auth.uid()))))) and public.mfa_verified_or_grace());

-- agent_messages:agent_messages_select_own (cmd=SELECT)
alter policy "agent_messages_select_own" on public.agent_messages
  using (((EXISTS ( SELECT 1    FROM (agent_conversations c      JOIN accounts a ON ((a.id = c.user_id)))   WHERE ((c.id = agent_messages.conversation_id) AND (a.data_user_id = auth.uid()))))) and public.mfa_verified_or_grace());

-- agent_nudges:agent_nudges_select_own (cmd=SELECT)
alter policy "agent_nudges_select_own" on public.agent_nudges
  using (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.id = agent_nudges.user_id) AND (a.data_user_id = auth.uid()))))) and public.mfa_verified_or_grace());

-- agent_nudges:agent_nudges_update_own_status (cmd=UPDATE)
alter policy "agent_nudges_update_own_status" on public.agent_nudges
  using (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.id = agent_nudges.user_id) AND (a.data_user_id = auth.uid()))))) and public.mfa_verified_or_grace())
  with check (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.id = agent_nudges.user_id) AND (a.data_user_id = auth.uid()))))) and public.mfa_verified_or_grace());

-- attendance_marks:owner read attendance_marks (cmd=SELECT)
alter policy "owner read attendance_marks" on public.attendance_marks
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- attendance_marks:owner write attendance_marks (cmd=ALL)
alter policy "owner write attendance_marks" on public.attendance_marks
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- cleaning_events:owner rw cleaning_events (cmd=ALL)
alter policy "owner rw cleaning_events" on public.cleaning_events
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- daily_logs:owner rw daily_logs (cmd=ALL)
alter policy "owner rw daily_logs" on public.daily_logs
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- dashboard_by_date:owner rw dashboard_by_date (cmd=ALL)
alter policy "owner rw dashboard_by_date" on public.dashboard_by_date
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- deep_clean_config:owner rw deep_clean_config (cmd=ALL)
alter policy "owner rw deep_clean_config" on public.deep_clean_config
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- deep_clean_records:owner rw deep_clean_records (cmd=ALL)
alter policy "owner rw deep_clean_records" on public.deep_clean_records
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- demand_predictions:owner read demand_predictions (cmd=SELECT)
alter policy "owner read demand_predictions" on public.demand_predictions
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- demand_priors:auth read demand_priors (cmd=SELECT)
alter policy "auth read demand_priors" on public.demand_priors
  using ((true) and public.mfa_verified_or_grace());

-- guest_requests:owner rw guest_requests (cmd=ALL)
alter policy "owner rw guest_requests" on public.guest_requests
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- handoff_logs:owner rw handoff_logs (cmd=ALL)
alter policy "owner rw handoff_logs" on public.handoff_logs
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- hotel_join_codes:hotel_join_codes_manage_for_own_hotels (cmd=ALL)
alter policy "hotel_join_codes_manage_for_own_hotels" on public.hotel_join_codes
  using ((user_owns_property(hotel_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(hotel_id)) and public.mfa_verified_or_grace());

-- inventory:owner rw inventory (cmd=ALL)
alter policy "owner rw inventory" on public.inventory
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- inventory_budgets:owner rw inventory_budgets (cmd=ALL)
alter policy "owner rw inventory_budgets" on public.inventory_budgets
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- inventory_counts:owner rw inventory_counts (cmd=ALL)
alter policy "owner rw inventory_counts" on public.inventory_counts
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- inventory_discards:owner rw inventory_discards (cmd=ALL)
alter policy "owner rw inventory_discards" on public.inventory_discards
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- inventory_orders:owner rw inventory_orders (cmd=ALL)
alter policy "owner rw inventory_orders" on public.inventory_orders
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- inventory_rate_predictions:owner read inventory_rate_predictions (cmd=SELECT)
alter policy "owner read inventory_rate_predictions" on public.inventory_rate_predictions
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- inventory_rate_priors:auth read inventory_rate_priors (cmd=SELECT)
alter policy "auth read inventory_rate_priors" on public.inventory_rate_priors
  using ((true) and public.mfa_verified_or_grace());

-- inventory_reconciliations:owner rw inventory_reconciliations (cmd=ALL)
alter policy "owner rw inventory_reconciliations" on public.inventory_reconciliations
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- laundry_config:owner rw laundry_config (cmd=ALL)
alter policy "owner rw laundry_config" on public.laundry_config
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- manager_notifications:owner rw manager_notifications (cmd=ALL)
alter policy "owner rw manager_notifications" on public.manager_notifications
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- ml_feature_flags:owner read ml_feature_flags (cmd=SELECT)
alter policy "owner read ml_feature_flags" on public.ml_feature_flags
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- ml_feature_flags:owner write ml_feature_flags (cmd=ALL)
alter policy "owner write ml_feature_flags" on public.ml_feature_flags
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- model_runs:owner read model_runs (cmd=SELECT)
alter policy "owner read model_runs" on public.model_runs
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- optimizer_results:owner read optimizer_results (cmd=SELECT)
alter policy "owner read optimizer_results" on public.optimizer_results
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- plan_snapshots:owner rw plan_snapshots (cmd=ALL)
alter policy "owner rw plan_snapshots" on public.plan_snapshots
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- prediction_log:owner read prediction_log (cmd=SELECT)
alter policy "owner read prediction_log" on public.prediction_log
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- prediction_overrides:owner insert prediction_overrides (cmd=INSERT)
alter policy "owner insert prediction_overrides" on public.prediction_overrides
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- prediction_overrides:owner read prediction_overrides (cmd=SELECT)
alter policy "owner read prediction_overrides" on public.prediction_overrides
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- preventive_tasks:owner rw preventive_tasks (cmd=ALL)
alter policy "owner rw preventive_tasks" on public.preventive_tasks
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- properties:account can read properties (cmd=SELECT)
alter policy "account can read properties" on public.properties
  using ((user_owns_property(id)) and public.mfa_verified_or_grace());

-- properties:admin can delete properties (cmd=DELETE)
alter policy "admin can delete properties" on public.properties
  using (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.data_user_id = auth.uid()) AND (a.role = 'admin'::text))))) and public.mfa_verified_or_grace());

-- properties:admin can insert properties (cmd=INSERT)
alter policy "admin can insert properties" on public.properties
  with check (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.data_user_id = auth.uid()) AND (a.role = 'admin'::text))))) and public.mfa_verified_or_grace());

-- properties:admin can update properties (cmd=UPDATE)
alter policy "admin can update properties" on public.properties
  using (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.data_user_id = auth.uid()) AND (a.role = 'admin'::text))))) and public.mfa_verified_or_grace())
  with check (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.data_user_id = auth.uid()) AND (a.role = 'admin'::text))))) and public.mfa_verified_or_grace());

-- property_shift_presets:property_shift_presets_select (cmd=SELECT)
alter policy "property_shift_presets_select" on public.property_shift_presets
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- public_areas:owner rw public_areas (cmd=ALL)
alter policy "owner rw public_areas" on public.public_areas
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- rooms:housekeeper read own rooms (cmd=SELECT)
alter policy "housekeeper read own rooms" on public.rooms
  using (((EXISTS ( SELECT 1    FROM staff s   WHERE ((s.id = rooms.assigned_to) AND (s.auth_user_id = auth.uid()))))) and public.mfa_verified_or_grace());

-- rooms:owner rw rooms (cmd=ALL)
alter policy "owner rw rooms" on public.rooms
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- schedule_assignments:owner rw schedule_assignments (cmd=ALL)
alter policy "owner rw schedule_assignments" on public.schedule_assignments
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- scheduled_shifts:scheduled_shifts_select (cmd=SELECT)
alter policy "scheduled_shifts_select" on public.scheduled_shifts
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- scraper_status:authenticated can read scraper_status (cmd=SELECT)
alter policy "authenticated can read scraper_status" on public.scraper_status
  using (((auth.role() = 'authenticated'::text)) and public.mfa_verified_or_grace());

-- shift_confirmations:owner rw shift_confirmations (cmd=ALL)
alter policy "owner rw shift_confirmations" on public.shift_confirmations
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- staff:housekeeper read own staff row (cmd=SELECT)
alter policy "housekeeper read own staff row" on public.staff
  using (((auth_user_id = auth.uid())) and public.mfa_verified_or_grace());

-- staff:owner rw staff (cmd=ALL)
alter policy "owner rw staff" on public.staff
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- supply_predictions:owner read supply_predictions (cmd=SELECT)
alter policy "owner read supply_predictions" on public.supply_predictions
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- supply_priors:auth read supply_priors (cmd=SELECT)
alter policy "auth read supply_priors" on public.supply_priors
  using ((true) and public.mfa_verified_or_grace());

-- time_off_requests:time_off_requests_select (cmd=SELECT)
alter policy "time_off_requests_select" on public.time_off_requests
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- walkthrough_runs:walkthrough_runs_select_own (cmd=SELECT)
alter policy "walkthrough_runs_select_own" on public.walkthrough_runs
  using (((EXISTS ( SELECT 1    FROM accounts a   WHERE ((a.id = walkthrough_runs.user_id) AND (a.data_user_id = auth.uid()))))) and public.mfa_verified_or_grace());

-- week_publications:week_publications_select (cmd=SELECT)
alter policy "week_publications_select" on public.week_publications
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

-- work_orders:owner rw work_orders (cmd=ALL)
alter policy "owner rw work_orders" on public.work_orders
  using ((user_owns_property(property_id)) and public.mfa_verified_or_grace())
  with check ((user_owns_property(property_id)) and public.mfa_verified_or_grace());

notify pgrst, 'reload schema';

insert into public.applied_migrations (version, description)
values (
  '0161',
  'Audit 2026-05-22 Phase 2B: RLS sweep — 57 policies now AND-gated on mfa_verified_or_grace().'
)
on conflict (version) do nothing;
