// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/consent" | "/dashboard" | "/front-desk" | "/housekeeper" | "/housekeeper/[id]" | "/housekeeping" | "/inventory" | "/laundry" | "/laundry/[id]" | "/maintenance" | "/onboarding" | "/privacy" | "/property-selector" | "/roi" | "/settings" | "/settings/accounts" | "/settings/operations" | "/settings/pms" | "/settings/property" | "/settings/staff" | "/signin" | "/staff" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/backfill-phonelookup" | "/api/admin/diagnose" | "/api/admin/doctor" | "/api/admin/normalize-confirmation-phones" | "/api/admin/test-sms-flow" | "/api/auth/accounts" | "/api/auth/login" | "/api/confirmation" | "/api/cron/scraper-health" | "/api/cron/scraper-weekly-digest" | "/api/help-request" | "/api/morning-resend" | "/api/notify-backup" | "/api/notify-housekeepers" | "/api/notify-housekeepers-sms" | "/api/populate-rooms-from-plan" | "/api/save-fcm-token" | "/api/seed-staff" | "/api/send-shift-confirmations" | "/api/sms-reply" | "/api/staff-list" | "/api/sync-room-assignments" | "/api/test-sms"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/backfill-phonelookup": {}
  "/api/admin/diagnose": {}
  "/api/admin/doctor": {}
  "/api/admin/normalize-confirmation-phones": {}
  "/api/admin/test-sms-flow": {}
  "/api/auth/accounts": {}
  "/api/auth/login": {}
  "/api/confirmation": {}
  "/api/cron/scraper-health": {}
  "/api/cron/scraper-weekly-digest": {}
  "/api/help-request": {}
  "/api/morning-resend": {}
  "/api/notify-backup": {}
  "/api/notify-housekeepers": {}
  "/api/notify-housekeepers-sms": {}
  "/api/populate-rooms-from-plan": {}
  "/api/save-fcm-token": {}
  "/api/seed-staff": {}
  "/api/send-shift-confirmations": {}
  "/api/sms-reply": {}
  "/api/staff-list": {}
  "/api/sync-room-assignments": {}
  "/api/test-sms": {}
  "/consent": {}
  "/dashboard": {}
  "/front-desk": {}
  "/housekeeper": {}
  "/housekeeper/[id]": { "id": string; }
  "/housekeeping": {}
  "/inventory": {}
  "/laundry": {}
  "/laundry/[id]": { "id": string; }
  "/maintenance": {}
  "/onboarding": {}
  "/privacy": {}
  "/property-selector": {}
  "/roi": {}
  "/settings": {}
  "/settings/accounts": {}
  "/settings/operations": {}
  "/settings/pms": {}
  "/settings/property": {}
  "/settings/staff": {}
  "/signin": {}
  "/staff": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
