// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consent">> = Specific
  const handler = {} as typeof import("../../../src/app/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/front-desk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/front-desk">> = Specific
  const handler = {} as typeof import("../../../src/app/front-desk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/housekeeper/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/housekeeper/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/housekeeper/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/housekeeper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/housekeeper">> = Specific
  const handler = {} as typeof import("../../../src/app/housekeeper/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/housekeeping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/housekeeping">> = Specific
  const handler = {} as typeof import("../../../src/app/housekeeping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/laundry/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laundry/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/laundry/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/laundry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laundry">> = Specific
  const handler = {} as typeof import("../../../src/app/laundry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../../src/app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/property-selector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/property-selector">> = Specific
  const handler = {} as typeof import("../../../src/app/property-selector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/roi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roi">> = Specific
  const handler = {} as typeof import("../../../src/app/roi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/accounts">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/operations">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/pms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/pms">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/pms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/property/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/property">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/property/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../../src/app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/backfill-phonelookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/backfill-phonelookup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/backfill-phonelookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/diagnose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diagnose">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/diagnose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/doctor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/doctor">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/doctor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/normalize-confirmation-phones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalize-confirmation-phones">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/normalize-confirmation-phones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/test-sms-flow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/test-sms-flow">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/test-sms-flow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/accounts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/confirmation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/scraper-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/scraper-health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/scraper-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/scraper-weekly-digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/scraper-weekly-digest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/scraper-weekly-digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/help-request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/help-request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/help-request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/morning-resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/morning-resend">> = Specific
  const handler = {} as typeof import("../../../src/app/api/morning-resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notify-backup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify-backup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notify-backup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notify-housekeepers-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify-housekeepers-sms">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notify-housekeepers-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notify-housekeepers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify-housekeepers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notify-housekeepers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/populate-rooms-from-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/populate-rooms-from-plan">> = Specific
  const handler = {} as typeof import("../../../src/app/api/populate-rooms-from-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/save-fcm-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/save-fcm-token">> = Specific
  const handler = {} as typeof import("../../../src/app/api/save-fcm-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/seed-staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-staff">> = Specific
  const handler = {} as typeof import("../../../src/app/api/seed-staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/send-shift-confirmations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-shift-confirmations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/send-shift-confirmations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sms-reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sms-reply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sms-reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff-list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff-list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff-list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sync-room-assignments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync-room-assignments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sync-room-assignments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/test-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-sms">> = Specific
  const handler = {} as typeof import("../../../src/app/api/test-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
