// Pure helper for CountSheet's idempotent transactional save. The fingerprint
// determines whether a click is a retry of the same payload (reuse the request
// UUID) or a newly edited count (start a new request UUID).

/** Value snapshot of the typed entries, so a retry can tell whether it is
 *  resuming the same count (resume: skip completed steps) or the user edited
 *  numbers after the failure (start a fresh attempt). Order-insensitive. */
export function entriesFingerprint(entries: Record<string, { value: string }>): string {
  return Object.keys(entries)
    .filter((id) => entries[id].value !== '')
    .sort()
    .map((id) => {
      const raw = entries[id].value;
      const numeric = Number(raw);
      // "5", "5.0", and "05" produce the same RPC payload and therefore
      // must share one idempotency key after an ambiguous response.
      return `${id}=${Number.isFinite(numeric) ? String(numeric) : raw}`;
    })
    .join('|');
}

// Inline item creation still uses the legacy insert helper, whose row UUID is
// generated by Postgres. A dropped response therefore cannot be retried safely:
// the first insert may already exist. Persist this exact envelope before the
// insert and put its unguessable request marker in the row's notes. Realtime can
// then prove that the insert landed; until it does, the UI fails closed instead
// of issuing a second insert.
export type InlineAddScope = 'general' | 'breakfast' | 'all';

export interface FrozenInlineAddAttempt {
  version: 1;
  propertyId: string;
  requestId: string;
  startedAt: string;
  scope: InlineAddScope;
  nameInput: string;
  quantityInput: string;
  parInput: string;
  costInput: string;
  name: string;
  quantity: number;
  parLevel: number;
  unitCost: number | null;
  category: 'housekeeping' | 'breakfast';
}

type StorageLike = Pick<Storage, 'getItem' | 'setItem' | 'removeItem'>;

export class InlineAddAttemptPersistenceError extends Error {
  readonly code = 'INLINE_ADD_ATTEMPT_NOT_DURABLE';

  constructor() {
    super('The inline item attempt could not be verified in local storage.');
    this.name = 'InlineAddAttemptPersistenceError';
  }
}

function browserStorage(): StorageLike | null {
  if (typeof window === 'undefined') return null;
  try { return window.localStorage; } catch { return null; }
}

function finiteNonnegativeOrZero(raw: string): number {
  const value = Number(raw);
  return Number.isFinite(value) && value >= 0 ? value : 0;
}

export function inlineAddAttemptMarker(requestId: string): string {
  return `staxis:inline-count-add:${requestId}`;
}

export function inlineAddAttemptStorageKey(propertyId: string): string {
  return `staxis:inventory-inline-add-attempt:${propertyId}`;
}

export function createFrozenInlineAddAttempt(input: {
  propertyId: string;
  requestId: string;
  startedAt: string;
  scope: InlineAddScope;
  nameInput: string;
  quantityInput: string;
  parInput: string;
  costInput: string;
}): FrozenInlineAddAttempt {
  const propertyId = input.propertyId.trim();
  const requestId = input.requestId.trim();
  const name = input.nameInput.trim();
  if (!propertyId) throw new Error('Property id is required for an inline item.');
  if (!requestId) throw new Error('Request id is required for an inline item.');
  if (!name) throw new Error('Item name is required.');
  if (Number.isNaN(new Date(input.startedAt).getTime())) throw new Error('Inline item timestamp is invalid.');

  const costNumber = input.costInput.trim() === '' ? null : Number(input.costInput);
  const unitCost = costNumber != null && Number.isFinite(costNumber) && costNumber >= 0
    ? costNumber
    : null;
  return {
    version: 1,
    propertyId,
    requestId,
    startedAt: input.startedAt,
    scope: input.scope,
    nameInput: input.nameInput,
    quantityInput: input.quantityInput,
    parInput: input.parInput,
    costInput: input.costInput,
    name,
    quantity: finiteNonnegativeOrZero(input.quantityInput),
    parLevel: finiteNonnegativeOrZero(input.parInput),
    unitCost,
    category: input.scope === 'breakfast' ? 'breakfast' : 'housekeeping',
  };
}

function isFrozenInlineAddAttempt(value: unknown): value is FrozenInlineAddAttempt {
  if (!value || typeof value !== 'object') return false;
  const x = value as Partial<FrozenInlineAddAttempt>;
  if (x.version !== 1
    || typeof x.propertyId !== 'string'
    || typeof x.requestId !== 'string'
    || typeof x.startedAt !== 'string'
    || (x.scope !== 'general' && x.scope !== 'breakfast' && x.scope !== 'all')
    || typeof x.nameInput !== 'string'
    || typeof x.quantityInput !== 'string'
    || typeof x.parInput !== 'string'
    || typeof x.costInput !== 'string'
    || typeof x.name !== 'string'
    || typeof x.quantity !== 'number'
    || typeof x.parLevel !== 'number'
    || (x.unitCost !== null && typeof x.unitCost !== 'number')
    || (x.category !== 'housekeeping' && x.category !== 'breakfast')) return false;
  try {
    const canonical = createFrozenInlineAddAttempt(x as FrozenInlineAddAttempt);
    return canonical.propertyId === x.propertyId
      && canonical.requestId === x.requestId
      && canonical.startedAt === x.startedAt
      && canonical.scope === x.scope
      && canonical.nameInput === x.nameInput
      && canonical.quantityInput === x.quantityInput
      && canonical.parInput === x.parInput
      && canonical.costInput === x.costInput
      && canonical.name === x.name
      && canonical.quantity === x.quantity
      && canonical.parLevel === x.parLevel
      && canonical.unitCost === x.unitCost
      && canonical.category === x.category;
  } catch {
    return false;
  }
}

export function persistInlineAddAttempt(
  attempt: FrozenInlineAddAttempt,
  storage: StorageLike | null = browserStorage(),
): void {
  if (!storage) throw new InlineAddAttemptPersistenceError();
  const key = inlineAddAttemptStorageKey(attempt.propertyId);
  const serialized = JSON.stringify(attempt);
  try {
    storage.setItem(key, serialized);
    // Some restricted/private storage implementations silently ignore writes.
    // An exact readback is therefore part of the pre-send contract, not merely
    // a test convenience. No verified bytes means no inventory insert.
    if (storage.getItem(key) !== serialized) throw new InlineAddAttemptPersistenceError();
  } catch {
    try { storage.removeItem(key); } catch {}
    throw new InlineAddAttemptPersistenceError();
  }
}

export function loadInlineAddAttempt(
  propertyId: string,
  storage: StorageLike | null = browserStorage(),
): FrozenInlineAddAttempt | null {
  if (!storage) return null;
  try {
    const raw = storage.getItem(inlineAddAttemptStorageKey(propertyId));
    if (!raw) return null;
    const parsed: unknown = JSON.parse(raw);
    return isFrozenInlineAddAttempt(parsed) && parsed.propertyId === propertyId ? parsed : null;
  } catch {
    return null;
  }
}

export function clearInlineAddAttempt(
  propertyId: string,
  storage: StorageLike | null = browserStorage(),
): void {
  if (!storage) return;
  try { storage.removeItem(inlineAddAttemptStorageKey(propertyId)); } catch {}
}

export function findInlineAddCommittedItem<T extends {
  propertyId: string;
  notes?: string;
}>(attempt: FrozenInlineAddAttempt, items: readonly T[]): T | null {
  const marker = inlineAddAttemptMarker(attempt.requestId);
  return items.find((item) => item.propertyId === attempt.propertyId && item.notes === marker) ?? null;
}
